In [1]:
from parameters import *
from functions import *

In [2]:
df_per_game = get_stats('per_game')
df_per_game

Season 2013 - Shape (596, 30)
Season 2014 - Shape (635, 30)
Season 2015 - Shape (675, 30)
Season 2016 - Shape (601, 30)
Season 2017 - Shape (619, 30)
Season 2018 - Shape (690, 30)
Season 2019 - Shape (734, 30)
Season 2020 - Shape (677, 30)
Season 2021 - Shape (731, 30)
Season 2022 - Shape (842, 30)
Season 2023 - Shape (705, 30)
Column names - Done
Data saved in data/raw/nba_per_game_2013_2023.csv

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season
0,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,.485,...,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2,2023
1,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,.597,...,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6,2023
2,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,.540,...,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4,2023
3,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,.427,...,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9,2023
4,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,.470,...,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7500,Nick Young,SG,27,PHI,59,17,23.9,3.8,9.2,.413,...,0.4,1.8,2.2,1.4,0.6,0.2,0.8,1.4,10.6,2013
7501,Sam Young,SG,27,IND,56,3,12.4,1.0,2.6,.392,...,0.5,1.7,2.2,0.8,0.3,0.1,0.6,1.1,2.8,2013
7502,Thaddeus Young,PF,24,PHI,76,76,34.6,6.7,12.6,.531,...,2.4,5.1,7.5,1.6,1.8,0.7,1.2,2.5,14.8,2013
7503,Luke Zeller,C,25,PHO,16,0,3.6,0.6,1.6,.346,...,0.1,0.6,0.6,0.2,0.0,0.0,0.0,0.3,1.2,2013
7504,Tyler Zeller,C,23,CLE,77,55,26.4,3.2,7.3,.438,...,2.1,3.6,5.7,1.2,0.5,0.9,1.2,3.3,7.9,2013

In [3]:
df_play_by_play = get_stats('play-by-play')
df_play_by_play

Season 2013 - Shape (596, 23)
Season 2014 - Shape (635, 23)
Season 2015 - Shape (675, 23)
Season 2016 - Shape (601, 23)
Season 2017 - Shape (619, 23)
Season 2018 - Shape (690, 23)
Season 2019 - Shape (734, 23)
Season 2020 - Shape (677, 23)
Season 2021 - Shape (731, 23)
Season 2022 - Shape (842, 23)
Season 2023 - Shape (705, 23)
Column names - Done
Data saved in data/raw/nba_play-by-play_2013_2023.csv

,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,PF%,...,BadPass,LostBall,Fouls Commited Shoot,Fouls Commited Off,Fouls Drawn Shoot,Fouls Drawn Off,PGA,And1,Blkd,Season
0,Precious Achiuwa,C,23,TOR,55,1140,NaN,NaN,NaN,17,...,8,21,53,19,59,7,128,15,31,2023
1,Steven Adams,C,29,MEM,42,1133,NaN,NaN,NaN,NaN,...,40,10,40,23,51,7,223,15,14,2023
2,Bam Adebayo,C,25,MIA,75,2598,NaN,NaN,NaN,NaN,...,61,46,86,50,196,10,587,37,49,2023
3,Ochai Agbaji,SG,22,UTA,59,1209,38,40,20,3,...,15,8,65,9,32,3,159,4,20,2023
4,Santi Aldama,PF,22,MEM,77,1682,NaN,NaN,2,69,...,19,20,93,11,48,11,231,12,20,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7500,Nick Young,SG,27,PHI,59,1411,9,65,26,1,...,14,23,41,7,61,12,188,12,18,2013
7501,Sam Young,SG,27,IND,56,693,NaN,69,31,NaN,...,22,2,28,3,17,4,102,3,9,2013
7502,Thaddeus Young,PF,24,PHI,76,2629,NaN,NaN,NaN,97,...,36,39,100,7,93,10,283,18,50,2013
7503,Luke Zeller,C,25,PHO,16,58,NaN,NaN,NaN,NaN,...,0,0,4,0,0,0,6,0,0,2013
7504,Tyler Zeller,C,23,CLE,77,2033,NaN,NaN,NaN,NaN,...,30,27,154,17,62,20,224,11,49,2013

In [4]:
df_advanced = get_stats('advanced')
df_advanced

Season 2013 - Shape (596, 29)
Season 2014 - Shape (635, 29)
Season 2015 - Shape (675, 29)
Season 2016 - Shape (601, 29)
Season 2017 - Shape (619, 29)
Season 2018 - Shape (690, 29)
Season 2019 - Shape (734, 29)
Season 2020 - Shape (677, 29)
Season 2021 - Shape (731, 29)
Season 2022 - Shape (842, 29)
Season 2023 - Shape (705, 29)
Column names - Done
Data saved in data/raw/nba_advanced_2013_2023.csv

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Season
0,Precious Achiuwa,C,23,TOR,55,1140,15.2,.554,.267,.307,...,19.4,0.8,1.4,2.2,.093,-1.4,-0.8,-2.3,-0.1,2023
1,Steven Adams,C,29,MEM,42,1133,17.5,.564,.004,.490,...,14.6,1.3,2.1,3.4,.144,-0.3,0.9,0.6,0.7,2023
2,Bam Adebayo,C,25,MIA,75,2598,20.1,.592,.011,.361,...,25.2,3.6,3.8,7.4,.137,0.8,0.8,1.5,2.3,2023
3,Ochai Agbaji,SG,22,UTA,59,1209,9.5,.561,.591,.179,...,15.8,0.9,0.4,1.3,.053,-1.7,-1.4,-3.0,-0.3,2023
4,Santi Aldama,PF,22,MEM,77,1682,13.9,.591,.507,.274,...,16.0,2.1,2.4,4.6,.130,-0.3,0.8,0.5,1.1,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7500,Nick Young,SG,27,PHI,59,1411,13.3,.525,.387,.236,...,21.2,1.4,1.0,2.3,.079,-0.1,-0.6,-0.7,0.5,2013
7501,Sam Young,SG,27,IND,56,693,7.5,.464,.351,.291,...,13.2,-0.2,1.1,0.9,.062,-3.5,0.8,-2.7,-0.1,2013
7502,Thaddeus Young,PF,24,PHI,76,2629,18.2,.541,.008,.196,...,19.8,3.7,3.7,7.4,.136,0.2,1.0,1.2,2.1,2013
7503,Luke Zeller,C,25,PHO,16,58,5.6,.365,.192,.000,...,19.9,-0.1,0.0,-0.1,-0.047,-4.1,-3.0,-7.2,-0.1,2013
7504,Tyler Zeller,C,23,CLE,77,2033,11.0,.486,.007,.281,...,15.9,0.8,1.2,2.0,.048,-3.1,-0.9,-4.0,-1.0,2013

In [2]:
df_contract = get_contracts()
df_contract

Column names - done
Data saved in data/0_raw/nba_contracts.csv

/Users/montevideolabs/Documents/Code/functions.py:91: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table_html))[0]

,Player,Tm,2023-24 Salary,2024-25 Salary,2025-26 Salary,2026-27 Salary,2027-28 Salary,2028-29 Salary,Guaranteed
0,Stephen Curry,GSW,"$51,915,615","$55,761,216","$59,606,817",NaN,NaN,NaN,"$167,283,648"
1,Kevin Durant,PHO,"$47,649,433","$51,179,021","$54,708,609",NaN,NaN,NaN,"$153,537,063"
2,Nikola Jokić,DEN,"$47,607,350","$51,415,938","$55,224,526","$59,033,114","$62,841,702",NaN,"$213,280,928"
3,Joel Embiid,PHI,"$47,607,350","$51,415,938","$55,224,526","$59,033,114",NaN,NaN,"$154,247,814"
4,LeBron James,LAL,"$47,607,350","$51,415,938",NaN,NaN,NaN,NaN,"$47,607,350"
...,...,...,...,...,...,...,...,...,...
521,Nerlens Noel,SAC,"$300,000",NaN,NaN,NaN,NaN,NaN,"$300,000"
522,Didi Louzada,POR,"$268,032","$268,032","$268,032","$268,032","$268,032","$268,032","$1,608,192"
523,Neemias Queta,SAC,"$250,000",NaN,NaN,NaN,NaN,NaN,"$250,000"
524,Danny Green,PHI,"$200,000",NaN,NaN,NaN,NaN,NaN,"$200,000"
525,Demetrius Jackson,BOS,"$92,857",NaN,NaN,NaN,NaN,NaN,"$92,857"

In [6]:
df_players_bio = get_players_bio()
df_players_bio

Data gathering - done
Data saved in data/raw/nba_players_bio.csv

,Name,Position,Shoots,Height-Weight,Date Born,College,Draft,NBA Debut,Experience,Player Image
0,Stephen Curry,[ Point Guard],[ Right],"[(188cm, 83kg)]",[1988-03-14],"[ href=""/friv/colleges.fcgi?college=davidson"">...","[ href=""/teams/GSW/draft.html"">Golden State Wa...","[ href=""/boxscores/200910280GSW.html"">October ...",[ 14 years],https://www.basketball-reference.com/req/20210...
1,Kevin Durant,"[ Small Forward, Power Forward, and Shooting G...",[ Right],"[(208cm, 108kg)]",[1988-09-29],"[ href=""/friv/colleges.fcgi?college=texas"">Texas]","[ href=""/teams/OKC/draft.html"">Seattle SuperSo...","[ href=""/boxscores/200710310DEN.html"">October ...",[ 15 years],https://www.basketball-reference.com/req/20210...
2,Nikola Jokić,[ Center],[ Right],"[(211cm, 128kg)]",[1995-02-19],[],"[ href=""/teams/DEN/draft.html"">Denver Nuggets<...","[ href=""/boxscores/201510280HOU.html"">October ...",[ 8 years],https://www.basketball-reference.com/req/20210...
3,Joel Embiid,[ Center],[ Right],"[(213cm, 127kg)]",[1994-03-16],"[ href=""/friv/colleges.fcgi?college=kansas"">Ka...","[ href=""/teams/PHI/draft.html"">Philadelphia 76...","[ href=""/boxscores/201610260PHI.html"">October ...",[ 7 years],https://www.basketball-reference.com/req/20210...
4,LeBron James,"[ Small Forward, Power Forward, Point Guard, C...",[ Right],"[(206cm, 113kg)]",[1984-12-30],[],"[ href=""/teams/CLE/draft.html"">Cleveland Caval...","[ href=""/boxscores/200310290SAC.html"">October ...",[ 20 years],https://www.basketball-reference.com/req/20210...
...,...,...,...,...,...,...,...,...,...,...
479,Lamar Stevens,[ Power Forward and Small Forward],[ Right],"[(198cm, 104kg)]",[1997-07-09],"[ href=""/friv/colleges.fcgi?college=pennst"">Pe...",[],"[ href=""/boxscores/202012270CLE.html"">December...",[ 3 years],https://www.basketball-reference.com/req/20210...
480,Nerlens Noel,[ Center and Power Forward],[ Right],"[(211cm, 99kg)]",[1994-04-10],"[ href=""/friv/colleges.fcgi?college=kentucky"">...","[ href=""/teams/NOH/draft.html"">New Orleans Hor...","[ href=""/boxscores/201410290IND.html"">October ...",[ 9 years],https://www.basketball-reference.com/req/20210...
481,Didi Louzada,[ Small Forward and Shooting Guard],[ Right],"[(196cm, 85kg)]",[1999-02-07],[],"[ href=""/teams/ATL/draft.html"">Atlanta Hawks</...","[ href=""/boxscores/202105120DAL.html"">May 12, ...",[ 2 years],https://www.basketball-reference.com/req/20210...
482,Neemias Queta,[ Center],[ Right],"[(213cm, 111kg)]",[1999-07-13],"[ href=""/friv/colleges.fcgi?college=utahst"">Ut...","[ href=""/teams/SAC/draft.html"">Sacramento King...","[ href=""/boxscores/202112170SAC.html"">December...",[ 2 years],https://www.basketball-reference.com/req/20210...
483,Demetrius Jackson,[ Point Guard],[ Right],"[(185cm, 91kg)]",[1994-09-07],"[ href=""/friv/colleges.fcgi?college=notredame""...","[ href=""/teams/BOS/draft.html"">Boston Celtics<...","[ href=""/boxscores/201611060BOS.html"">November...",[],https://www.basketball-reference.com/req/20210...